-- V9: Enhancements for settlements, late fees, extra fees, and receipts
ALTER TABLE settlements MODIFY COLUMN ContractID BIGINT NULL;

ALTER TABLE settlements
    ADD COLUMN DepositHeld DECIMAL(15, 0) NOT NULL DEFAULT 0 AFTER StaffID,
    ADD COLUMN LateFee DECIMAL(15, 0) NOT NULL DEFAULT 0 AFTER DamageReason,
    ADD COLUMN ExtraFee DECIMAL(15, 0) NOT NULL DEFAULT 0 AFTER RefundAmount,
    ADD COLUMN Status VARCHAR(30) NOT NULL DEFAULT 'FINALIZED' AFTER ExtraFee,
    ADD COLUMN Notes VARCHAR(500) NULL AFTER Status,
    ADD COLUMN CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER Notes;
